server:
  port: 9090

app:
  url: http://localhost:9090/

spring:
  application:
    name: production

  datasource:
    url: jdbc:postgresql://localhost:5432/prod_db
    driverClassName: org.postgresql.Driver
    username: user
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never
      schema-locations: classpath:sql/postgres_schema.sql
      data-locations: classpath:sql/postgres_data.sql

  data:
    rest:
      base-path: /api
